### ISSUE TITLE
VS Mode Crash

### ISSUE THREAD

**Issue by Zachruff** [mkw-sp/mkw-sp#751]
![image](https://github.com/stblr/mkw-sp/assets/70397032/5faa194a-c0bb-46c0-825c-86e8894bb2d5)

Using these settings:
![image](https://github.com/stblr/mkw-sp/assets/70397032/97a07b13-d06c-4da6-82b4-0b19f2cac0f3)
![image](https://github.com/stblr/mkw-sp/assets/70397032/691bd1e9-0ef5-43a2-a2a9-8da866d80647)

**Comment by stblr** [comment]
We should maybe just block single player VS races without CPUs.

**Comment by Zachruff** [comment]
Agree. Though does the current settings system allow for that? Or is that something I'll have to figure out eventually?

**Comment by stblr** [comment]
We could have a dedicated check.
