### ISSUE TITLE
Thumnails should be indexed by SHA1, not WiimmID

### ISSUE THREAD

**Issue by riidefi** [mkw-sp/mkw-sp#784]

**Comment by GnomedDev** [comment]
Will be closed by #655

**Comment by riidefi** [comment]
I would personally rather see this addressed first

**Comment by GnomedDev** [comment]
It would cause duplication of effort, as track-packs is tied into it's new system, it would have to be reimplemented on master and not reduce the diff of track-packs, if that is what you are worried about reducing.

**Comment by riidefi** [comment]
I think it would be a stepping stone to both #655 and #785? Would it be a terrible amount of effort to just use SaveManager::s_courseSHA1s to get these SHA1s in the meanwhile?

**Comment by GnomedDev** [comment]
Should be closed after #833

**Comment by riidefi** [comment]
Good point
