### ISSUE TITLE
Discussion: Swap Protobuf for Capn Proto

### ISSUE THREAD

**Issue by GnomedDev** [mkw-sp/mkw-sp#872]
https://capnproto.org/ seems to be made by the same author as protobuf 2, and it's claim of zero serialisation/deserialisation time seems pretty good, alongside similar serialised/packed wire format, and a much better syntax for message definition.

We probably need to evaluate if we can use this on the Wii, as well as if it's arena based allocation can be hooked into the Heap system.

I propose if we are to implement this, testing it out on matchmaking first, due to it being low priority (unusable now) and I have written the whole thing.

**Comment by stblr** [comment]
We need to stay compatible with the update server.

**Comment by GnomedDev** [comment]
The update server can maintain a legacy route for protobuf compatibility.

**Comment by stblr** [comment]
That discussion already happened one year ago and for better or worse one solution was chosen. Here I clearly don't think the technical burden of maintaining 2 separate systems for doing the same thing can be justified.

**Comment by GnomedDev** [comment]
Where is this discussion? I don't believe we should be holding the project back by past decisions in such an alpha state, especially when the burden of maintaining two systems is a couple dozen lines of code at most.

**Comment by stblr** [comment]
https://discord.com/channels/932046805171044482/932048315082756187/989395845067718667

**Comment by GnomedDev** [comment]
That doesn't look like a discussion of different pros and cons of different options, that looks like "oh protobuf looks cool". I've read the documentation of this and it looks nicer to write and with less/no read/write overhead for encoding.

**Comment by stblr** [comment]
Then you maybe saw that this requires a POSIX system as well as dynamic memory allocation which makes it completely unsuitable for what we are doing. On the Wii, the networking hardware is always going to be a bottleneck before the CPU. The current nanopb system doesn't have any of these drawbacks and is not "holding back" the project in any way.

**Comment by GnomedDev** [comment]
Dynamic memory allocation can be solved by a providing a buffer, which could be backed by a heap, but okay.
